name: mytestapp

services:
  dev-web-app:
    build:
      context: .
      dockerfile: ./docker/dev-docker.Dockerfile
    ports:
      - 8085:8080
    volumes:
      - ./:/app
    networks:
      - web-apps
  
  postgres-db:
    image: postgres:15
    environment:
      POSTGRES_USER: example
      POSTGRES_DB: exampledb
    networks:
      - web-apps

networks:
  web-apps: