name: mytestapp

services:
  test-web-app-1:
    build:
      context: .
      dockerfile: ./docker/dev-docker.Dockerfile
    ports:
      - 8085:8080
    volumes:
      - ./TestWebApplications/:/app
    networks:
      - web-apps
  
  postgres-db:
    image: postgres:15
    environment:
      POSTGRES_USER: example
      POSTGRES_DB: exampledb
    networks:
      - web-apps


networks:
  web-apps: